import { Lesson } from '../types/lesson.types.js';

const lesson: Lesson = {
  day: 15,
  subject: 'earth-science',
  title: 'Oceans & Currents - The Blue Heart of Planet Earth',
  emoji: '🌊',
  learningGoal: 'Understand ocean structure, properties, and the powerful global circulation systems that regulate Earth\'s climate',
  estimatedTime: 70,
  objectives: [
    'Describe the zones and physical properties of the ocean',
    'Explain how ocean currents form and what drives them',
    'Distinguish between surface currents and deep ocean currents',
    'Understand the global ocean conveyor belt and its climate impacts',
    'Recognize the importance of oceans in regulating Earth\'s temperature and weather'
  ],

  discoveryStory: {
    title: 'Benjamin Franklin and the Mystery of the Atlantic Crossing',
    content: "It's 1768, and Benjamin Franklin (yes, the kite-and-lightning guy!) is stumped by a bizarre mystery. British mail ships from England to America take TWO WEEKS LONGER than American merchant ships, even though they\'re newer and supposedly faster! As deputy postmaster, Franklin is determined to solve this. He consults his cousin Timothy Folger, a Nantucket whaling captain, who reveals an incredible secret: 'The British captains are sailing AGAINST a massive river in the ocean!' This 'river' was the Gulf Stream - a powerful ocean current flowing north along the American coast. American captains knew to avoid it when sailing east, while clueless British captains fought against it! Franklin and Folger created the FIRST MAP of an ocean current, showing this invisible highway of warm water moving at 5.6 mph (faster than you walk!). Franklin\'s discovery revolutionized navigation, but more importantly, he\'d uncovered the key to understanding how oceans move heat around our planet. Today we know the Gulf Stream is part of a global ocean conveyor belt that keeps Europe 9°C warmer than it should be. One mystery solved, one planet-changing system discovered! 🌊🗺️",
    emoji: '⛵'
  },

  keyTerms: [
    {
      term: 'Salinity',
      definition: 'The amount of dissolved salts in ocean water, measured in parts per thousand (ppt) or practical salinity units (PSU)',
      example: 'Average ocean salinity is 35 ppt (3.5%) - that means 35 grams of salt in 1,000 grams of water, or about 1 cup of salt per gallon'
    },
    {
      term: 'Ocean Current',
      definition: 'A continuous, directed movement of ocean water generated by forces like wind, Earth\'s rotation, temperature, and salinity differences',
      example: 'The Gulf Stream current moves warm water from the Gulf of Mexico northward along the eastern US coast at speeds up to 5.6 mph'
    },
    {
      term: 'Thermocline',
      definition: 'A layer in the ocean where temperature decreases rapidly with depth, separating warm surface water from cold deep water',
      example: 'Between 200-1000m depth, temperature can drop from 20°C to 4°C - like going from room temperature to refrigerator in a few hundred meters!'
    },
    {
      term: 'Upwelling',
      definition: 'The process where deep, cold, nutrient-rich water rises to the ocean surface, typically along coasts',
      example: 'The California coast has upwelling zones where cold water brings nutrients that feed massive populations of fish and whales'
    },
    {
      term: 'Thermohaline Circulation',
      definition: 'Global deep ocean current driven by differences in water density (affected by temperature and salinity) - also called the "ocean conveyor belt"',
      example: 'Cold, salty water sinks in the North Atlantic, travels through all oceans, and takes 1,000 years to complete the global loop!'
    },
    {
      term: 'Coriolis Effect',
      definition: 'The deflection of moving objects (including ocean currents and winds) due to Earth\'s rotation - rightward in Northern Hemisphere, leftward in Southern Hemisphere',
      example: 'Ocean currents curve clockwise in the North Atlantic and counterclockwise in the South Atlantic due to Coriolis effect'
    }
  ],

  concepts: [
    {
      title: 'The Ocean: Earth\'s Blue Blanket',
      explanation: 'Oceans cover 71% of Earth\'s surface and contain 97% of Earth\'s water. They\'re not uniform - they have layers, zones, and properties that vary with depth and location.',
      analogy: {
        type: 'Ocean as Layered Cake',
        description: 'Think of the ocean as a giant layered cake with different properties at each depth:\n\n**SURFACE ZONE (0-200m): The Sunlit Frosting**\n• Warm (varies by location: 0-30°C)\n• Bright (sunlight penetrates - photosynthesis happens!)\n• Most life lives here (fish, plankton, kelp)\n• Mixed by wind and waves\n\n**THERMOCLINE (200-1000m): The Temperature Drop**\n• Temperature drops RAPIDLY (20°C → 4°C)\n• Transition zone between warm surface and cold deep\n• Acts like an insulating blanket separating layers\n\n**DEEP ZONE (1000m-bottom): The Cold Dark Basement**\n• Cold (2-4°C everywhere on Earth)\n• Dark (zero sunlight - pitch black!)\n• High pressure (would crush you like a soda can)\n• Slow-moving, ancient water (can be 1,000 years old)\n\nIt\'s like a reverse atmosphere: instead of getting colder as you go UP (like air), oceans get colder as you go DOWN!'
      },
      mindBlowingFacts: [
        'If you drained all ocean water, the ocean floor has taller mountains (Mauna Kea: 10,200m from base to peak) and deeper canyons (Mariana Trench: 11,000m deep) than any on land!',
        'Ocean water at the deepest point has pressure 1,100× greater than at the surface - enough to crush a submarine like an empty soda can',
        'The oceans contain 50× more carbon than the atmosphere - they\'re Earth\'s biggest carbon sink and climate buffer!'
      ],
      whyYouCare: 'Oceans regulate Earth\'s temperature by absorbing heat (preventing Earth from overheating), produce 50-80% of Earth\'s oxygen (from phytoplankton), and drive global weather patterns. No oceans = no life as we know it!'
    },

    {
      title: 'Salinity: The Ocean\'s Salt Content',
      explanation: 'Ocean water is salty because rivers constantly dissolve minerals from rocks and carry them to the sea. Water evaporates, but salt stays - concentrating over millions of years.',
      analogy: {
        type: 'The Evaporating Salt Bowl',
        description: 'Imagine you put a cup of saltwater in the sun:\n• Water evaporates → disappears into air\n• Salt stays behind → can\'t evaporate\n• Cup gets saltier and saltier over time\n\nNow scale this up to EARTH:\n1. **RIVERS ADD SALT:** Rain dissolves tiny amounts of salt from rocks → rivers carry it to ocean (too little to taste)\n2. **SUN REMOVES WATER:** Solar energy evaporates pure water from ocean surface (salt stays behind)\n3. **SALT ACCUMULATES:** Over 4 billion years, oceans have gotten saltier and saltier\n4. **EQUILIBRIUM REACHED:** Now salt added = salt removed (buried in sediments), so salinity is stable at 35 ppt\n\n**SALINITY VARIES:**\n• **HIGH salinity (>36 ppt):** Hot dry areas (Mediterranean, Red Sea) - lots of evaporation, little rain\n• **AVERAGE salinity (35 ppt):** Open ocean\n• **LOW salinity (<34 ppt):** Near river mouths (Amazon, Mississippi), polar regions (melting ice adds freshwater)\n\nIt\'s like Earth\'s oldest chemistry experiment - 4 billion years of salt concentration!'
      },
      mindBlowingFacts: [
        'If you evaporated all ocean water, the remaining salt would form a layer 500 feet (152m) thick covering all continents!',
        'The Dead Sea has 34% salinity (340 ppt) - nearly 10× saltier than oceans - you float like a cork because the dense water holds you up!',
        'A cubic mile of ocean water contains about 120 million tons of salt - enough to cover all of Texas in a 5-foot-deep layer!'
      ],
      whyYouCare: 'Salinity affects ocean density (drives deep currents), freezing point (salty water freezes at -2°C, not 0°C), and marine life (fish must constantly regulate salt balance). Understanding salinity is crucial for climate science and marine biology!'
    },

    {
      title: 'Surface Currents: Wind-Driven Ocean Highways',
      explanation: 'Surface currents are like massive rivers in the ocean, driven primarily by global wind patterns and modified by Earth\'s rotation (Coriolis effect).',
      analogy: {
        type: 'Giant Conveyor Belts of Water',
        description: 'Imagine the ocean surface has invisible conveyor belts moving water:\n\n**WHAT DRIVES THEM:**\n1. **WIND (main driver):** Trade winds and westerlies push water\n2. **CORIOLIS EFFECT:** Earth\'s rotation curves currents (right in Northern Hemisphere, left in Southern)\n3. **CONTINENTS:** Land masses deflect currents, creating gyres (circular patterns)\n\n**MAJOR SURFACE CURRENTS:**\n\n🔴 **WARM CURRENTS (from equator toward poles):**\n• Gulf Stream (Atlantic) - warms Western Europe\n• Kuroshio Current (Pacific) - warms Japan\n• Brazil Current (South Atlantic)\n• Think: Heating ducts carrying warmth from tropics\n\n🔵 **COLD CURRENTS (from poles toward equator):**\n• California Current (Pacific) - cools US West Coast\n• Peru/Humboldt Current (South Pacific) - creates deserts\n• Labrador Current (North Atlantic) - brings icebergs south\n• Think: Air conditioning bringing cold from poles\n\n**GYRES (circular patterns):**\n• North Atlantic Gyre (clockwise)\n• North Pacific Gyre (clockwise) - has the Great Pacific Garbage Patch!\n• South Atlantic/Pacific Gyres (counterclockwise)\n• Think: Giant whirlpools of slow-moving currents'
      },
      mindBlowingFacts: [
        'The Gulf Stream transports 30× more water than ALL rivers on Earth COMBINED - about 100 million cubic meters per second!',
        'Rubber duckies spilled from a cargo ship in 1992 are STILL being tracked around the world by ocean currents - they\'ve circled the Pacific multiple times!',
        'Without the Gulf Stream, London would have the same climate as northern Canada (same latitude) - it would be frozen much of the year!'
      ],
      whyYouCare: 'Surface currents determine regional climates (why London is warmer than Labrador), fishing zones (nutrients concentrate where currents meet), navigation routes, and even where ocean plastic accumulates!'
    },

    {
      title: 'Deep Ocean Currents: The Thermohaline Conveyor Belt',
      explanation: 'While surface currents are wind-driven, deep ocean currents are driven by density differences caused by temperature (thermo-) and salinity (-haline). This creates a global conveyor belt.',
      analogy: {
        type: 'The Global Lava Lamp',
        description: 'Remember lava lamps? Blobs rise (hot, less dense) and sink (cool, more dense). The ocean does the same on a planetary scale!\n\n**THE PROCESS:**\n\n1. **NORTH ATLANTIC SINKING:**\n• Warm Gulf Stream water reaches Arctic\n• Evaporation makes it saltier\n• Cold + salty = VERY DENSE\n• Dense water SINKS (like lava lamp blobs cooling and sinking)\n• This is the "engine" of the conveyor belt!\n\n2. **DEEP CURRENT TRAVELS:**\n• Sunken water flows south along ocean floor\n• Travels through Atlantic → around Antarctica → into Indian and Pacific Oceans\n• Journey takes 1,000+ years!\n\n3. **UPWELLING AND RETURN:**\n• Deep water slowly rises in Pacific/Indian Oceans\n• Warms and becomes less dense\n• Surface currents carry it back toward Atlantic\n• Cycle completes!\n\n**WHY IT MATTERS:**\n• Carries oxygen to deep ocean (allows deep-sea life)\n• Stores carbon dioxide for centuries (climate regulation)\n• Distributes heat globally (keeps Earth habitable)\n• If it stopped, Europe would freeze and tropics would overheat!\n\nIt\'s like Earth\'s central heating/cooling system - a planetary-scale climate control mechanism!'
      },
      mindBlowingFacts: [
        'Water in the deep Pacific Ocean fell as rain 1,000-2,000 YEARS AGO - before Columbus, before the Roman Empire fell!',
        'If global warming melts too much Greenland ice (adding freshwater), it could shut down the Atlantic conveyor belt - this happened 12,000 years ago and plunged Europe into an ice age!',
        'The thermohaline circulation moves about 100× slower than surface currents - about 0.01 mph (but it moves VASTLY more water overall)'
      ],
      whyYouCare: 'The ocean conveyor belt regulates global climate, stores CO₂ from the atmosphere (fighting climate change), distributes nutrients for marine food chains, and keeps deep oceans oxygenated. It\'s literally Earth\'s life support system!'
    },

    {
      title: 'Upwelling: Bringing the Deep to the Surface',
      explanation: 'Upwelling occurs when winds or currents push surface water away from an area, and cold, nutrient-rich deep water rises to replace it.',
      analogy: {
        type: 'The Ocean\'s Refrigerator Opening',
        description: 'Imagine upwelling like opening a refrigerator in a hot room:\n\n**NORMAL OCEAN (no upwelling):**\n• Warm surface water (like warm room air)\n• Nutrients trapped in cold deep water (like food locked in fridge)\n• Low biological productivity\n\n**UPWELLING ZONE:**\n1. **WIND BLOWS:** Coastal winds push surface water offshore (Coriolis effect helps)\n2. **COLD WATER RISES:** Deep water (2-4°C) rushes up to fill the gap\n3. **NUTRIENTS ARRIVE:** Deep water is LOADED with nutrients (from decomposed organisms that sank)\n4. **LIFE EXPLODES:** Phytoplankton feast on nutrients → multiply like crazy → feed fish → feed whales → MASSIVE food chain\n\n**MAJOR UPWELLING ZONES:**\n• California coast\n• Peru coast (Humboldt Current)\n• West coast of Africa\n• Antarctica\n\nThese zones cover <1% of ocean area but produce >50% of world\'s fish catch!\n\nIt\'s like the ocean\'s version of bringing vitamins up from a deep storage cellar - instant productivity boost!'
      },
      mindBlowingFacts: [
        'Upwelling zones support the largest fisheries on Earth - Peru\'s anchovy fishery is the world\'s largest by tonnage!',
        'When El Niño shuts down upwelling in the Pacific, fish populations crash, seabirds starve, and global weather patterns change',
        'Upwelling brings water to the surface that hasn\'t seen sunlight in centuries - it\'s like time-traveling water from the deep past!'
      ],
      whyYouCare: 'Upwelling zones produce most of the world\'s seafood, support massive marine ecosystems (whales, seabirds, seals), and influence coastal climates (creating fog and cool temperatures). Changes in upwelling due to climate change directly threaten global food security!'
    },

    {
      title: 'Oceans and Climate: The Blue Thermostat',
      explanation: 'Oceans are Earth\'s climate regulators, absorbing heat, storing carbon, and distributing both globally through currents.',
      analogy: {
        type: 'The Ocean as Planetary Air Conditioner',
        description: 'Think of oceans as a massive climate control system:\n\n**HEAT REGULATION:**\n• **High heat capacity:** Water heats/cools slowly (like thermal mass in buildings)\n• **Absorbs 93% of excess heat** from greenhouse gases (protecting land from extreme warming)\n• **Distributes heat:** Warm currents → heat poles, Cold currents → cool tropics\n• Result: Smaller temperature extremes globally\n\n**CARBON STORAGE:**\n• **Absorbs 25% of human CO₂ emissions** from atmosphere\n• **Phytoplankton photosynthesize:** Using CO₂, producing oxygen (50-80% of Earth\'s O₂!)\n• **Deep ocean storage:** Carbon sinks to bottom, locked away for centuries\n• Problem: Absorbing CO₂ makes oceans more acidic (threatens marine life)\n\n**WATER CYCLE ENGINE:**\n• **Evaporation:** Provides moisture for rain/snow\n• **Hurricane fuel:** Warm water powers tropical storms\n• **Weather patterns:** Ocean temps determine El Niño, monsoons, droughts\n\n**WITHOUT OCEANS:**\n• Day-night temperature swings of 100°C+ (like the Moon)\n• No rain (no water cycle)\n• Atmospheric CO₂ 100× higher (no ocean absorption)\n• Basically, Earth would be Mars\n\nOceans are literally the reason Earth is habitable!'
      },
      mindBlowingFacts: [
        'Oceans have absorbed heat equivalent to detonating 5 Hiroshima atomic bombs PER SECOND for the last 25 years - yet the average ocean temperature has only risen 0.1°C (showing their massive heat capacity)',
        'If oceans didn\'t absorb CO₂, atmospheric CO₂ would be 50% HIGHER than current levels - we\'d be in catastrophic warming already',
        'The top 3 meters of ocean stores as much heat as the ENTIRE atmosphere above it - water is 1,000× denser than air!'
      ],
      whyYouCare: 'Understanding ocean-climate connections explains: why islands have mild climates, why El Niño causes global droughts and floods, why climate change is making oceans warmer and more acidic, and why protecting oceans is critical for fighting climate change!'
    }
  ],

  workedExamples: [
    {
      scenario: 'Predicting Current Direction with Coriolis Effect',
      problemSetup: 'Trade winds blow from east to west across the Atlantic Ocean at the equator. Predict the direction of the resulting surface current in:\na) The Northern Hemisphere (near the Tropic of Cancer)\nb) The Southern Hemisphere (near the Tropic of Capricorn)',
      steps: [
        {
          step: 1,
          description: 'Identify the initial wind direction: East → West (winds blow water westward)',
          reasoning: 'Wind is the primary driver of surface currents - water moves in the direction wind pushes it (initially)'
        },
        {
          step: 2,
          description: 'Recall Coriolis effect rules:\n• Northern Hemisphere: Deflects moving objects to the RIGHT\n• Southern Hemisphere: Deflects moving objects to the LEFT',
          reasoning: 'Earth\'s rotation causes this deflection - it affects all moving fluids on Earth\'s surface'
        },
        {
          step: 3,
          description: 'Apply to Northern Hemisphere:\n• Initial direction: West (from wind)\n• Coriolis deflects RIGHT (from perspective looking west)\n• Result: Current curves NORTHWEST',
          reasoning: 'Deflection to the right of westward motion means northward curve'
        },
        {
          step: 4,
          description: 'Apply to Southern Hemisphere:\n• Initial direction: West (from wind)\n• Coriolis deflects LEFT (from perspective looking west)\n• Result: Current curves SOUTHWEST',
          reasoning: 'Deflection to the left of westward motion means southward curve'
        },
        {
          step: 5,
          description: 'Verify with reality: This creates GYRES (circular patterns)\n• Northern gyres spin CLOCKWISE\n• Southern gyres spin COUNTERCLOCKWISE',
          reasoning: 'This is exactly what we observe in the North and South Atlantic Gyres!'
        }
      ],
      solution: 'a) Northern Hemisphere: Current flows NORTHWEST (deflected right). b) Southern Hemisphere: Current flows SOUTHWEST (deflected left). This Coriolis deflection creates the circular gyre patterns in both hemispheres.',
      realWorldApplication: 'This is how the North Atlantic Gyre forms (clockwise circulation), creating the Gulf Stream along the US East Coast. Understanding Coriolis effect helps predict: ocean navigation routes, where oil spills will drift, and where ocean garbage accumulates (e.g., Great Pacific Garbage Patch)!'
    },

    {
      scenario: 'Density and Thermohaline Circulation',
      problemSetup: 'Compare two water samples:\nSample A: Temperature 5°C, Salinity 34 ppt\nSample B: Temperature 5°C, Salinity 37 ppt\n\nWhich sample is denser? If both were released in the ocean at the same location, which would sink deeper? Explain your reasoning.',
      steps: [
        {
          step: 1,
          description: 'Identify factors affecting water density:\n• TEMPERATURE: Colder = denser (molecules packed closer)\n• SALINITY: Saltier = denser (more dissolved material)',
          reasoning: 'Density determines whether water sinks or floats - denser water sinks beneath less dense water'
        },
        {
          step: 2,
          description: 'Compare temperatures: Both 5°C (same temperature)',
          reasoning: 'Temperature is equal, so this factor doesn\'t differentiate them'
        },
        {
          step: 3,
          description: 'Compare salinities:\n• Sample A: 34 ppt (below average)\n• Sample B: 37 ppt (above average - SALTIER)',
          reasoning: 'Sample B has more dissolved salt, making it denser'
        },
        {
          step: 4,
          description: 'Conclusion: Sample B is DENSER than Sample A',
          reasoning: 'Same temperature, but higher salinity means higher density'
        },
        {
          step: 5,
          description: 'Predict behavior: Sample B will SINK DEEPER than Sample A',
          reasoning: 'Denser water sinks below less dense water due to gravity - this is how thermohaline circulation works!'
        },
        {
          step: 6,
          description: 'Real-world connection: This happens in the North Atlantic\n• Warm water evaporates → increases salinity\n• Water cools in Arctic → decreases temperature\n• Cold + salty = very dense → SINKS\n• This drives the global conveyor belt!',
          reasoning: 'Thermohaline circulation is powered by density differences created by temperature and salinity changes'
        }
      ],
      solution: 'Sample B (37 ppt) is denser than Sample A (34 ppt) because higher salinity increases density. Sample B would sink deeper. This principle drives deep ocean currents in the thermohaline circulation.',
      realWorldApplication: 'This explains why Mediterranean water (high salinity from evaporation) sinks when it flows into the Atlantic. It also explains climate concerns: if Greenland ice melts (adding freshwater), the North Atlantic would become less salty, less dense, and might stop sinking - potentially shutting down the Gulf Stream and freezing Europe!'
    },

    {
      scenario: 'Upwelling and Fishery Productivity',
      problemSetup: 'The California coast has persistent northerly winds (blowing south along the coast). Using your knowledge of Coriolis effect and upwelling, explain:\n1. Why this causes upwelling\n2. Why California has such productive fisheries',
      steps: [
        {
          step: 1,
          description: 'Identify wind direction: Northerly winds blow SOUTH along the California coast',
          reasoning: 'Wind direction is the key driver of coastal upwelling'
        },
        {
          step: 2,
          description: 'Apply Coriolis effect: In Northern Hemisphere, moving water deflects RIGHT\n• Winds push surface water south\n• Coriolis deflects water to the RIGHT\n• Right of southward = OFFSHORE (away from coast)',
          reasoning: 'Coriolis effect causes surface water to move away from the coastline'
        },
        {
          step: 3,
          description: 'Predict water replacement: Surface water moves offshore → creates "gap"\n• Nature abhors a vacuum\n• Deep water RISES to fill the gap\n• This upward movement = UPWELLING',
          reasoning: 'Water must come from somewhere to replace surface water moving offshore - it comes from below'
        },
        {
          step: 4,
          description: 'Identify properties of upwelled water:\n• COLD (2-4°C from deep ocean)\n• NUTRIENT-RICH (nitrates, phosphates from decomposed organisms)\n• OXYGEN-RICH',
          reasoning: 'Deep water contains nutrients that have accumulated from sinking dead organisms'
        },
        {
          step: 5,
          description: 'Explain biological productivity:\n• Nutrients + Sunlight → PHYTOPLANKTON BLOOM\n• Phytoplankton → Zooplankton → Small fish → Big fish\n• Massive food chain = PRODUCTIVE FISHERY',
          reasoning: 'Nutrients are the limiting factor for ocean productivity - upwelling removes this limitation'
        }
      ],
      solution: '1) Northerly winds + Coriolis effect push surface water offshore → deep water rises to replace it = upwelling. 2) Upwelled water brings nutrients from the deep ocean → massive phytoplankton growth → feeds entire food chain → productive fisheries.',
      realWorldApplication: 'This is why California, Peru, and West Africa have massive fishing industries despite relatively small ocean areas. It also explains why El Niño (which shuts down upwelling) causes fishery collapses, economic crises in fishing communities, and seabird die-offs. Understanding upwelling is critical for managing fisheries and predicting climate impacts!'
    }
  ],

  practiceProblems: [
    {
      id: 'p1',
      question: 'London (51°N) has an average January temperature of 5°C, while Winnipeg, Canada (50°N - nearly the same latitude) averages -16°C. Explain this 21°C difference using your knowledge of ocean currents.',
      hints: [
        'Both cities are at nearly the same latitude - why is London so much warmer?',
        'What major warm current flows near Western Europe?',
        'Think about how the Gulf Stream transports heat from the tropics'
      ],
      difficulty: 'easy'
    },
    {
      id: 'p2',
      question: 'Explain why the Mediterranean Sea has higher salinity (38-39 ppt) than the average ocean (35 ppt). Consider climate, evaporation, and geography.',
      hints: [
        'The Mediterranean is nearly enclosed by land with a narrow connection to the Atlantic',
        'The region is hot and dry (evaporation rate is high)',
        'What happens to salinity when water evaporates but salt stays behind?',
        'Limited freshwater input from rivers compared to evaporation'
      ],
      difficulty: 'medium'
    },
    {
      id: 'p3',
      question: 'If global warming melts large amounts of Greenland ice (adding freshwater to the North Atlantic), predict how this would affect: a) Water density in the North Atlantic, b) The thermohaline circulation, c) European climate',
      hints: [
        'Freshwater is less dense than saltwater',
        'The thermohaline circulation depends on dense water sinking in the North Atlantic',
        'The Gulf Stream (part of this system) keeps Europe warm',
        'What happens if the "engine" of the conveyor belt weakens or stops?'
      ],
      difficulty: 'hard'
    },
    {
      id: 'p4',
      question: 'During El Niño, upwelling along the Peru coast weakens significantly. Predict the effects on: a) Ocean temperature, b) Fish populations, c) Seabird populations',
      hints: [
        'Upwelling normally brings cold, nutrient-rich water to the surface',
        'What happens when upwelling stops?',
        'Consider the food chain: nutrients → phytoplankton → fish → seabirds',
        'Think about what fish and seabirds eat and where they find food'
      ],
      difficulty: 'hard'
    },
    {
      id: 'p5',
      question: 'The Great Pacific Garbage Patch is a massive accumulation of plastic debris in the North Pacific. Using your knowledge of gyres and Coriolis effect, explain why garbage concentrates in this location rather than dispersing evenly across the ocean.',
      hints: [
        'The North Pacific Gyre is a circular current pattern',
        'What happens to floating debris in a rotating system?',
        'Think about the center of the gyre - where do currents move?',
        'Centripetal forces in rotating systems push objects toward the center'
      ],
      difficulty: 'hard'
    }
  ],

  quiz: [
    {
      id: 'q1',
      question: 'What is the average salinity of ocean water?',
      options: [
        { label: 'A', text: '3.5 ppt (parts per thousand)' },
        { label: 'B', text: '35 ppt (parts per thousand)' },
        { label: 'C', text: '350 ppt (parts per thousand)' },
        { label: 'D', text: '3,500 ppt (parts per thousand)' },
        { label: 'E', text: '50 ppt (parts per thousand)' }
      ],
      correctAnswer: 'B',
      explanation: 'Ocean water has an average salinity of 35 ppt, meaning 35 grams of dissolved salts per 1,000 grams of water, or 3.5%.',
      storyExplanation: 'Think of it as about 1 cup of salt dissolved in 1 gallon of water - salty enough to taste strongly, but not as salty as the Dead Sea (340 ppt)!'
    },

    {
      id: 'q2',
      question: 'What primarily drives surface ocean currents?',
      options: [
        { label: 'A', text: 'Differences in water density' },
        { label: 'B', text: 'Gravitational pull of the Moon' },
        { label: 'C', text: 'Global wind patterns' },
        { label: 'D', text: 'Underwater earthquakes' },
        { label: 'E', text: 'River flow into the ocean' }
      ],
      correctAnswer: 'C',
      explanation: 'Surface currents are primarily driven by global wind patterns (trade winds, westerlies). The Coriolis effect then deflects these currents.',
      storyExplanation: 'Think of winds as giant fans blowing across the ocean surface, pushing water in massive rivers called currents - the Gulf Stream is like a river in the ocean created by wind!'
    },

    {
      id: 'q3',
      question: 'The Gulf Stream carries warm water from the Gulf of Mexico toward Europe. What effect does this have on Western European climate?',
      options: [
        { label: 'A', text: 'Makes it much colder than other regions at the same latitude' },
        { label: 'B', text: 'Makes it much warmer than other regions at the same latitude' },
        { label: 'C', text: 'Has no effect on climate' },
        { label: 'D', text: 'Makes it much drier' },
        { label: 'E', text: 'Causes frequent hurricanes' }
      ],
      correctAnswer: 'B',
      explanation: 'The Gulf Stream transports warm tropical water to Western Europe, making it much warmer than other regions at the same latitude (e.g., London vs. Winnipeg, Canada).',
      storyExplanation: 'Without the Gulf Stream, London would be frozen like northern Canada! The current is like a giant heating duct carrying warmth from the Caribbean to Europe - that\'s why palm trees grow in parts of Ireland!'
    },

    {
      id: 'q4',
      question: 'What drives the deep ocean thermohaline circulation (ocean conveyor belt)?',
      options: [
        { label: 'A', text: 'Wind patterns' },
        { label: 'B', text: 'Tidal forces' },
        { label: 'C', text: 'Differences in water density (temperature and salinity)' },
        { label: 'D', text: 'Underwater volcanic activity' },
        { label: 'E', text: 'River input' }
      ],
      correctAnswer: 'C',
      explanation: 'Thermohaline circulation is driven by density differences caused by temperature (thermo-) and salinity (-haline). Cold, salty water is denser and sinks, driving the global conveyor belt.',
      storyExplanation: 'Think of it like a lava lamp on a planetary scale: cold salty water is dense and sinks (like cooled wax), warm fresh water is less dense and rises - this creates a 1,000-year cycle of deep ocean circulation!'
    },

    {
      id: 'q5',
      question: 'What is upwelling, and why is it important for marine life?',
      options: [
        { label: 'A', text: 'Rising warm water that kills fish' },
        { label: 'B', text: 'Rising cold, nutrient-rich water that feeds phytoplankton and supports fisheries' },
        { label: 'C', text: 'Sinking water that removes nutrients from the surface' },
        { label: 'D', text: 'Horizontal current along the coast' },
        { label: 'E', text: 'Wave action during storms' }
      ],
      correctAnswer: 'B',
      explanation: 'Upwelling brings cold, deep water (rich in nutrients from decomposed organisms) to the surface, where sunlight allows phytoplankton to bloom, supporting massive food chains.',
      storyExplanation: 'Upwelling is like the ocean opening its refrigerator and releasing all the stored nutrients to the surface - this creates an explosion of life, feeding the world\'s most productive fisheries!'
    }
  ],

  memoryAids: [
    {
      technique: 'Acronym',
      description: 'Remember what makes water DENSE: "COOLS" = COld + Salty = Sinks (high density)',
      example: 'Cold water + High salinity = Dense water that sinks (drives thermohaline circulation)'
    },
    {
      technique: 'Phrase',
      description: 'Coriolis deflection: "Northern Right, Southern Left" - moving objects deflect right in Northern Hemisphere, left in Southern Hemisphere',
      example: 'Use this to predict current directions: wind blows west → Coriolis deflects right (in north) → current goes northwest'
    },
    {
      technique: 'Visual',
      description: 'Remember gyres spin like HURRICANES: Clockwise in Northern Hemisphere (same as high-pressure systems), Counterclockwise in Southern Hemisphere',
      example: 'North Atlantic Gyre = clockwise circle, South Atlantic Gyre = counterclockwise circle'
    },
    {
      technique: 'Story',
      description: 'Ocean layers as "Cake": Sunlit Surface = frosting (warm, bright, alive), Thermocline = filling (temperature drops), Deep = dense base (cold, dark, ancient)',
      example: 'Use this to remember that temperature and light decrease with depth'
    },
    {
      technique: 'Rhyme',
      description: 'Upwelling rhyme: "Cold from deep brings nutrients to eat, making fisheries a treat!"',
      example: 'Use this to remember: upwelling = cold water + nutrients = productive fisheries'
    }
  ],

  commonMistakes: [
    {
      mistake: 'Thinking ocean currents are caused by tides',
      correction: 'Tides (caused by Moon\'s gravity) create local water level changes twice daily. Ocean CURRENTS are continuous flows driven by wind (surface) or density differences (deep) - completely different mechanisms!',
      whyItMatters: 'Understanding the actual drivers of currents (wind, density) is essential for predicting current patterns, climate effects, and navigation'
    },
    {
      mistake: 'Confusing surface currents with deep ocean currents',
      correction: 'SURFACE currents (top 400m) are driven by WIND and move relatively fast. DEEP currents (below 400m) are driven by DENSITY (temperature + salinity) and move very slowly. They\'re separate systems!',
      whyItMatters: 'The mechanisms are completely different, and they operate on different timescales (days/weeks for surface, centuries for deep). Climate change affects them differently'
    },
    {
      mistake: 'Thinking salinity is the same everywhere in the ocean',
      correction: 'Salinity VARIES: higher in hot dry regions (Mediterranean: 38 ppt), lower near river mouths (Amazon: 20 ppt) and polar regions (melting ice: 32 ppt). Average is 35 ppt.',
      whyItMatters: 'Salinity differences drive deep ocean currents and affect marine life distribution - fish are adapted to specific salinity ranges'
    },
    {
      mistake: 'Believing the ocean is too big to be affected by humans',
      correction: 'Oceans ARE being affected: warming (absorbing 93% of excess heat), acidifying (absorbing 25% of CO₂), overfished, polluted (Great Pacific Garbage Patch), coral bleaching. Oceans are changing FAST.',
      whyItMatters: 'This false belief delays action on climate change and ocean conservation. Understanding ocean vulnerability is critical for protecting Earth\'s life support systems'
    },
    {
      mistake: 'Thinking upwelling is just cold water rising',
      correction: 'Upwelling isn\'t just about TEMPERATURE - it\'s about NUTRIENTS! Cold water rises, but the KEY is that it brings deep nutrients (nitrates, phosphates) to the sunlit surface where phytoplankton can use them.',
      whyItMatters: 'The nutrients are what make upwelling zones so productive for fisheries - temperature alone wouldn\'t create the biological explosion'
    }
  ],

  quickReference: [
    {
      title: 'Ocean Zones by Depth',
      content: 'SURFACE (0-200m): Warm, sunlit, most life\nTHERMOCLINE (200-1000m): Rapid temperature drop\nDEEP (1000m-bottom): Cold (2-4°C), dark, high pressure',
      category: 'principle'
    },
    {
      title: 'Density Rules',
      content: 'DENSER (sinks): Colder, Saltier\nLESS DENSE (floats): Warmer, Fresher\nThermohaline = Thermo (temperature) + Haline (salinity)',
      category: 'rule'
    },
    {
      title: 'Surface vs Deep Currents',
      content: 'SURFACE: Driven by WIND, fast, top 400m, Coriolis effect creates gyres\nDEEP: Driven by DENSITY, slow, below 400m, global conveyor belt (1,000 year cycle)',
      category: 'principle'
    },
    {
      title: 'Coriolis Effect',
      content: 'NORTHERN HEMISPHERE: Deflects RIGHT (gyres clockwise)\nSOUTHERN HEMISPHERE: Deflects LEFT (gyres counterclockwise)\nCaused by Earth\'s rotation',
      category: 'rule'
    },
    {
      title: 'Upwelling Process',
      content: '1. Coastal winds push surface water offshore\n2. Coriolis effect enhances offshore movement\n3. Deep water rises to replace surface water\n4. Nutrients from deep ocean reach surface\n5. Phytoplankton bloom → productive fisheries',
      category: 'process'
    }
  ],

  summary: [
    'Oceans cover 71% of Earth and contain 97% of Earth\'s water, with properties varying by depth (temperature, light, pressure)',
    'Average ocean salinity is 35 ppt, varying by location (higher in hot dry areas, lower near rivers and ice)',
    'Surface currents are driven by wind and deflected by Coriolis effect (right in north, left in south), creating circular gyres',
    'Deep ocean currents (thermohaline circulation) are driven by density differences from temperature and salinity - the global conveyor belt takes 1,000 years to circulate',
    'Upwelling brings cold, nutrient-rich deep water to the surface, creating the world\'s most productive fisheries',
    'The Gulf Stream warms Western Europe by ~9°C, showing how ocean currents regulate regional climates',
    'Oceans regulate global climate by absorbing 93% of excess heat and 25% of human CO₂ emissions, producing 50-80% of Earth\'s oxygen',
    'Understanding oceans is critical for climate science, fisheries management, navigation, and predicting global weather patterns'
  ],

  selfAssessment: [
    'I can describe the three main ocean zones and how temperature/light/pressure change with depth',
    'I understand what salinity is and why it varies in different ocean regions',
    'I can explain how wind drives surface currents and how Coriolis effect creates gyres',
    'I understand the difference between surface currents (wind-driven) and deep currents (density-driven)',
    'I can explain how the thermohaline circulation works and why it matters for climate',
    'I can describe the upwelling process and explain why these zones are biologically productive',
    'I understand how ocean currents affect regional climates (like the Gulf Stream warming Europe)',
    'I can explain the role of oceans in regulating Earth\'s climate and absorbing CO₂'
  ]
};

export default lesson;
